#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored
def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)
    name=sys.argv[1]
    tweets=helpers.get_user_timeline(name, count=50)
    if tweets==None:
         sys.exit("User is private or doesn't exist")
    for t in tweets:
        score=analyzer.analyze(t)
        if score > 0.0:
            print(colored("{} {}".format(score, t), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, t), "red"))
        else:
            print(colored("{} {}".format(score, t), "yellow"))

if __name__ == "__main__":
    main()
